<?php
/**
 * Copyright (c) 2017 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
$locked = $block->isFeedLocked();
?>
<div>
    <div id="hawk_datagenerate_result" class="message-validation hidden"></div>
    <button type="button"
            id="<?=  /* @noEscape */ $block->getHtmlId() ?>">
        <span><?=  /* @noEscape */ $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <input type="checkbox"
           value="feedforce"
           id="<?=  /* @noEscape */ $block->getHtmlId() ?>_feedforce"
           name="feedforce"
           title="force data generation"/>
    <label for="<?=  /* @noEscape */ $block->getHtmlId() ?>_feedforce">force</label>
</div>

<script>
    require(['prototype'], function () {
        var locked = <?=  /* @noEscape */ $locked ? 'true' : 'false'; ?>;
        var b = $('<?=  /* @noEscape */ $block->getHtmlId() ?>');
        var cb = $('<?=  /* @noEscape */ $block->getHtmlId() ?>_feedforce');
        if (locked) {
            b.disable();
            cb.enable();
            cb.observe('click', function (event) {
                if (this.checked) {
                    b.enable();
                } else {
                    b.disable();
                }
            });
        } else {
            b.enable();
            cb.disable();
        }
        b.observe('click', function (event) {
            var isForce = cb.checked;
            new Ajax.Request('<?=  /* @noEscape */ $block->getGenerateUrl(); ?>', {
                parameters: {force: isForce},
                onSuccess: function (transport) {
                    var response = transport.responseText.evalJSON();
                    var responseEl = $("hawk_datagenerate_result");
                    if (response.error) {
                        responseEl.innerHTML = response.error;
                    } else {
                        responseEl.innerHTML = "Feed generation started";
                    }
                    responseEl.removeClassName('hidden');

                    b.disabled = true;
                    b.addClassName("disabled");
                    b.stopObserving('click');
                },
                onFailure: function (response, rHeader) {
                    alert('There has been an error. The response is: ' + response);
                    b.addClassName("disabled");
                    b.stopObserving('click');
                },
                onException: function (request, exception) {
                    alert('There has been an exception. The exceptions is: ' + exception);
                    b.addClassName("disabled");
                    b.stopObserving('click');
                }
            });
        });
    });
</script>

