<?php
/**
 * Created by PhpStorm.
 * User: mageuser
 * Date: 7/1/16
 * Time: 9:30 AM
 */
?>
<script>
require(['prototype'], function(){

//<![CDATA[
    function hawkGenerateFeed() {
        new Ajax.Request('<?php echo $block->getGenerateUrl(); ?>', {
            onSuccess: function (transport) {
                var response = transport.responseText.evalJSON();
                var responseEl = $("hawk_datagenerate_result");
                if (response.error) {
                    responseEl.innerHTML = response.error;
                    responseEl.removeClassName('hidden');
                    return;
                }
                responseEl.innerHTML = "Feed generation started";
                var button = $("<?php echo $block->getHtmlId(); ?>");
                button.disabled = true;
                button.addClassName("disabled");
            },
            onFailure: function (response, rHeader) {
                alert('There has been an error. The response is: ' + response);
            },
            onException: function (request, exception) {
                alert('There has been an exception. The exceptions is: ' + exception);
            }
        });
    }

    window.hawkGenerateFeed = hawkGenerateFeed;
//]]>

});
</script>

<div class="actions actions-validate-vat">
    <div id="hawk_datagenerate_result" class="message-validation hidden"></div>
    <button onclick="javascript:hawkGenerateFeed(); return false;"
            type="button"
            id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
